#!/bin/bash
# Quick Reference: IBiDAV 2.0 Commands

echo "═══════════════════════════════════════════════════════════════"
echo "          IBiDAV 2.0 - QUICK COMMAND REFERENCE"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "🚀 SETUP & DEPENDENCIES"
echo "  uv sync                             # Install dependencies"
echo "  uv run python -m spacy download en_core_web_sm  # Download NLP model"
echo ""

echo "📊 DATA & QUALITY ANALYSIS"
echo "  uv run scripts/prepare_training_data.py    # Create train/val/test splits"
echo "  uv run scripts/validate_data_quality.py    # Check label coverage"
echo "  uv run scripts/evaluate_search_quality.py  # Evaluate BM25 baseline"
echo ""

echo "🤖 MODEL TRAINING"
echo "  uv run scripts/train_label_classifier.py   # Train multi-label classifier (5-10 min)"
echo "  uv run scripts/train_semantic_topics.py    # Train BERTopic (10-20 min, optional)"
echo ""

echo "🧪 TESTING & MONITORING"
echo "  uv run scripts/test_search_quality.py      # CI/CD regression tests"
echo "  uv run scripts/monitor_label_quality.py    # Track improvement trends"
echo ""

echo "🚀 APPLICATION"
echo "  uv run ibidav-build-artifacts              # Build cached artifacts"
echo "  uv run uvicorn main:app --reload           # Start FastAPI server"
echo "  Open: http://127.0.0.1:8000"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "                    KEY FEATURES"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ spaCy NLP         - Modern preprocessing (replaces NLTK)"
echo "✅ Semantic Search   - BM25 + embeddings re-ranking"
echo "✅ Auto-labeling     - Predict labels for unlabeled articles"
echo "✅ Topic Discovery   - BERTopic semantic clustering"
echo "✅ CI/CD Testing     - Regression detection with GitHub Actions"
echo "✅ Quality Monitor   - Track label coverage improvements"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "                    RECOMMENDED WORKFLOW"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Setup:       uv sync && uv run python -m spacy download en_core_web_sm"
echo "2. Analyze:     uv run scripts/validate_data_quality.py"
echo "3. Split data:  uv run scripts/prepare_training_data.py"
echo "4. Train:       uv run scripts/train_label_classifier.py"
echo "5. Test:        uv run scripts/test_search_quality.py"
echo "6. Build:       uv run ibidav-build-artifacts"
echo "7. Run:         uv run uvicorn main:app --reload"
echo "8. Monitor:     uv run scripts/monitor_label_quality.py"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "                    FILE LOCATIONS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Core:     ibidav/"
echo "Scripts:  scripts/"
echo "Data:     data/splits/"
echo "Models:   .cache/models/"
echo "Artifacts:.cache/ibidav/"
echo "Monitoring:.cache/label_monitoring/"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "                    DOCUMENTATION"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📖 README.md                  - Feature overview & setup guide"
echo "📖 scripts/README.md          - Detailed script documentation"
echo "📖 IMPLEMENTATION_SUMMARY.md  - Technical implementation details"
echo ""

echo "═══════════════════════════════════════════════════════════════"
